src/ConjaWeb/Models/FeedbackViewData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConjaWeb.Models {
    public class FeedbackViewData {

        public string TalkSubject { get; set; }
        public string SpeakerName { get; set; }

        public int SessionId { get; set; }
        public Guid TalkGuid { get; set; }
        public string Enjoy { get; set; }
        public string Learn { get; set; }
        public string OneThingYouLiked { get; set; }
        public string OneIdeaToImprove { get; set; }

        public string SubmitterName { get; set; }
        public string SubmitterInfo { get; set; }

        public class Option {
            public string Name { get; set; }
            public string Value { get; set; }
            public bool Selected { get; set; }
            public string Label { get; set; }
        }

        private Option MakeOption(string value, string label, string currentValue) {
            return (new Option {
                Value = value,
                Label = label,
                Selected = currentValue == value
            });
        }


        public IEnumerable<Option> EnjoyOptions {
            get {
                yield return (MakeOption("zzz", "I was falling asleep...", this.Enjoy));
                yield return (MakeOption("meh", "It was OK, I guess", this.Enjoy));
                yield return (MakeOption("yes", "I liked it.", this.Enjoy));
                yield return (MakeOption("wow", "I loved it", this.Enjoy));
            }
        }

        public IEnumerable<Option> LearnOptions {
            get {
                yield return (MakeOption("err", "I found it confusing.", this.Learn));
                yield return (MakeOption("meh", "It was OK, I guess", this.Learn));
                yield return (MakeOption("yes", "I liked it.", this.Learn));
                yield return (MakeOption("wow", "I loved it", this.Learn));
            }
        }
    }
}

src/ConjaWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConjaWeb.Models;

namespace ConjaWeb.Controllers {
    public class HomeController : Controller {
        // GET: Home
        public ActionResult Index() {
            return View();
        }
    }

    public class TalksController : Controller {
        public ActionResult Feedback(string code) {
            var data = new FeedbackViewData();
            return (View(data));
        }

        [HttpPost]
        public ActionResult Feedback(FeedbackViewData post) {
            return (View(post));
        }
    }
}

src/ConjaWeb/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Conja</title>
    @Styles.Render("~/bundles/styles")
    @* Scripts.Render("~/bundles/modernizr") *@

</head>
<body>
    <header></header>
    <article>@RenderBody()</article>
    <footer>powered by conja</footer>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

src/ConjaWeb/Views/Talks/Feedback.cshtml
@model ConjaWeb.Models.FeedbackViewData

@{
    ViewBag.Title = "title";
}
<p>"Domain Architecture Isomorphism: I Fought Conway's Law (and the law won)"</p>
<p>Dylan Beattie</p>
<hr />
<form class="feedback" action="@Url.Action("Feedback", "Talks")" method="POST">
    <p>Did you enjoy the talk?</p>
    <fieldset>
        @foreach (var option in Model.EnjoyOptions) {
            <label for="enjoy-@option.Value" class="@option.Value @(option.Selected ? "active" : "")">
                <input type="radio" name="enjoy" value="@option.Value" id="enjoy-@option.Value"
                @(option.Selected ? "checked='checked'" : "") />
                @option.Label
            </label>
        }
    </fieldset>
    <p>Did you learn anything useful?</p>
    <fieldset>
        @foreach (var option in Model.LearnOptions) {
            <label for="learn-@option.Value" class="@option.Value @(option.Selected ? "active" : "")">
                <input type="radio" name="learn" value="@option.Value" id="learn-@option.Value"
                @(option.Selected ? "checked='checked'" : "") />
                @option.Label
            </label>
        }
    </fieldset>
    <div>
        <p>
            <label for="oneThingYouLiked">
                Share one thing you liked about this talk:
            </label>
        </p>
        <textarea name="oneThingYouLiked">@Model.OneThingYouLiked</textarea>
    </div>
    <div>
        <p>
            <label for="oneIdeaToImprove">
                Share one idea for making this talk better:
            </label>
        </p>
        <textarea name="oneIdeaToImprove">@Model.OneIdeaToImprove</textarea>

    </div>
    <!--
        <div>
            <p><label>Who are you? (optional!)</label></p>
            <p><input type="text" name="who_name" placeholder="Your full name" value="@Model."/></p>
            <p><input type="text" name="who_email" placeholder="email or Twitter name" /></p>
        </div>
        -->
    <div>
        <p>
            <input type="submit" value="Send Feedback" />
        </p>
    </div>
</form>
@section scripts
{
    <script>
        $(function () {
            $("form.feedback fieldset label").each(function () {
                $(this).attr("title", $(this).text());
            });
            $("form.feedback fieldset label").click(function () {
                var $this = $(this);
                $this.closest("fieldset").children("label").each(function () {
                    $(this).removeClass("active");
                });
                $(this).addClass("active");
            });

        });
    </script>
}